// The mushroom kinds that were drawn as text rather than by hand.
//
// The first seven kinds on the sheet are the artist's. These six are written
// here as grids, and this file is their source: change a grid and rerun
// tools/make-mushroom-colours.mjs to change the mushroom. A shape edit is then
// a reviewable diff of characters rather than an opaque change to a PNG — the
// same arrangement as the generated flowers in tools/make-flower-kinds.mjs.
//
// Each grid is the *inside* only; the outline is generated by the rule in
// tools/outline.mjs, which reproduces the hand-drawn caps pixel for pixel. Keep
// every coloured pixel at least two in from the edge, or its outline falls off
// the sprite (there is a test).
//
// Legend
//   b c   the cap, base and shade — the two colours every colour swaps
//   d     a fixed white
//   e f   the stem, shadow and lit — the drawn kinds' stem colours, never swapped
//   .     nothing
//
// A kind is coloured exactly the way the drawn ones are: every colour is the
// same grid with a different b/c pair, and the rainbow lays the drawn rainbow's
// seven colours across the cap in diagonal bands. Which colours a kind comes in
// is the sim's business (COLOURS in js/sim/mushrooms.js); what those names look
// like is CAPS below, plus GENERATED_COLOURS for the six generated ones.

import { isOutline } from './outline.mjs';
import { GENERATED_COLOURS } from '../js/sim/mushrooms.js';

const T = 16;

export const FIXED = {
  o: [63, 38, 49],
  d: [255, 255, 255],
  e: [189, 108, 74], f: [234, 165, 108],
};

/**
 * Base and shade for every drawn colour name a generated kind uses, read off
 * the drawn sheet. Where a name means slightly different pairs on different
 * drawn kinds (Tan, Orange), the bolete's is used — the cleanest two-colour one.
 */
export const CAPS = {
  Lime: { base: [153, 229, 80], shade: [106, 190, 48] },
  Cyan: { base: [95, 205, 228], shade: [65, 140, 156] },
  Frost: { base: [203, 219, 252], shade: [255, 255, 255] },
  Tan: { base: [193, 151, 108], shade: [203, 163, 122] },
  Orange: { base: [223, 113, 38], shade: [255, 153, 83] },
  Blue: { base: [115, 134, 250], shade: [91, 110, 225] },
  Spotted: { base: [172, 50, 50], shade: [255, 255, 255] },
  Red: { base: [232, 69, 55], shade: [255, 112, 109] },
  Green: { base: [55, 148, 110], shade: [106, 190, 48] },
  Pink: { base: [215, 123, 186], shade: [234, 146, 206] },
  Navy: { base: [63, 63, 116], shade: [91, 91, 156] },
  Umber: { base: [82, 75, 36], shade: [130, 121, 67] },
  Violet: { base: [177, 94, 151], shade: [234, 149, 207] },
  Brown: { base: [143, 86, 59], shade: [224, 132, 70] },
  Ash: { base: [89, 86, 82], shade: [130, 128, 125] },
  ...Object.fromEntries(GENERATED_COLOURS.map((c) => [c.name, { base: c.base, shade: c.shade }])),
};

/** The drawn rainbow's seven colours, red to violet. */
export const RAINBOW = [
  [221, 0, 0], [254, 98, 48], [254, 246, 0], [0, 187, 0], [0, 155, 254], [0, 0, 131], [48, 0, 155],
];

const NONE = ['................', '................', '................'];

export const DESIGNS = {
  // A trumpet: wide wavy rim, narrowing to the ground, one colour all over.
  chanterelle: [
    '................',
    '................',
    '................',
    '....bbb..bbb....',
    '...bbbbbbbbbb...',
    '...bccbbbbccb...',
    '....bccbbccb....',
    '.....bcbbcb.....',
    '......cbbc......',
    '......bbbb......',
    '.......bb.......',
    '.......bb.......',
    '......bbbb......',
    ...NONE,
  ],
  // A tall bullet with a ragged hem — the gaps fill with outline and drip.
  inkcap: [
    '................',
    '................',
    '......bbbb......',
    '.....bbcbbb.....',
    '.....bbbbcb.....',
    '.....bcbbbb.....',
    '.....bbbcbb.....',
    '.....cbbbbb.....',
    '.....bbcbbc.....',
    '.....b.b.b.b....',
    '.......ff.......',
    '.......ef.......',
    '.......ff.......',
    ...NONE,
  ],
  // A ball on the grass. No stem: the only kind without one.
  puffball: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '......bbbb......',
    '.....bbbcbb.....',
    '....bbcbbbbb....',
    '....bbbbbbcb....',
    '....bcbbbbbb....',
    '....bbbbcbbb....',
    '.....cbbbbc.....',
    '......cccc......',
    ...NONE,
  ],
  // Branches. The narrow gaps between them fill with outline, which is what
  // makes them read as separate arms.
  coral: [
    '................',
    '................',
    '...b...b...b....',
    '...b..bb..bb....',
    '...bb.b..bb.....',
    '....bbb..b...b..',
    '.....bbbbb..bb..',
    '..b...bbb..bb...',
    '..bb..bbbbbb....',
    '...bbbbbbb......',
    '.....cbbbc......',
    '......cbc.......',
    '......ccc.......',
    ...NONE,
  ],
  // A ball sitting in a star of split skin. The star is stem-coloured, so it
  // stays the same in every colour and only the ball changes.
  earthstar: [
    '................',
    '................',
    '................',
    '................',
    '.......bb.......',
    '......bbbb......',
    '.....bcbbbb.....',
    '.....bbbbcb.....',
    '..f..cbbbbc..f..',
    '..ff.ecccce.ff..',
    '...ffeeeeeeff...',
    '..fffffeefffff..',
    '.....ff..ff.....',
    ...NONE,
  ],
  // Three little caps on thin stems from one root: the only kind that grows as
  // a bunch.
  bonnet: [
    '................',
    '................',
    '................',
    '......bbb.......',
    '.....bbbbb......',
    '...b..cfc..bb...',
    '..bbb..f..bbbb..',
    '..cfc..f..cbbc..',
    '...f...f...f....',
    '...f...f...f....',
    '....f..f..f.....',
    '.....f.f.f......',
    '......fff.......',
    ...NONE,
  ],
};

/**
 * One 16x16 sprite, outline included.
 *
 * @param {string[]} rows   a design
 * @param {{base: number[], shade: number[]} | 'rainbow'} cap
 */
export function build(rows, cap) {
  if (rows.length !== T || rows.some((r) => r.length !== T)) {
    throw new Error(`a design is ${T}x${T}: got ${rows.map((r) => r.length).join(',')}`);
  }
  const grid = rows.map((r) => [...r]);
  for (const row of grid) {
    for (const c of row) {
      if (c !== '.' && c !== 'b' && c !== 'c' && !FIXED[c]) throw new Error(`no colour for "${c}"`);
    }
  }
  const inside = (x, y) => y >= 0 && y < T && x >= 0 && x < T
    && grid[y][x] !== '.' && grid[y][x] !== 'o';

  // The rainbow runs corner to corner across the cap in diagonal bands, shared
  // out over the diagonals the cap actually covers — so a bunch of separate
  // little caps, with empty diagonals between them, still gets every colour.
  const diagonals = new Set();
  grid.forEach((row, y) => row.forEach((c, x) => { if (c === 'b' || c === 'c') diagonals.add(x + y); }));
  const order = [...diagonals].sort((a, b) => a - b);
  const band = (x, y) => RAINBOW[Math.floor(order.indexOf(x + y) * RAINBOW.length / order.length)];

  const rgba = Buffer.alloc(T * T * 4);
  for (let y = 0; y < T; y++) {
    for (let x = 0; x < T; x++) {
      const c = grid[y][x];
      let rgb;
      if (c === '.') {
        if (!isOutline(inside, x, y)) continue;
        rgb = FIXED.o;
      } else if (c === 'b' || c === 'c') {
        rgb = cap === 'rainbow' ? band(x, y) : (c === 'b' ? cap.base : cap.shade);
      } else {
        rgb = FIXED[c];
      }
      const i = (y * T + x) * 4;
      rgba[i] = rgb[0]; rgba[i + 1] = rgb[1]; rgba[i + 2] = rgb[2]; rgba[i + 3] = 255;
    }
  }
  return rgba;
}

/**
 * Every sprite of one kind, in sheet order: one per colour name, the last
 * always the rainbow.
 * @param {string} kind
 * @param {string[]} colours  the kind's colour names, as COLOURS lists them
 */
export function buildKind(kind, colours) {
  const rows = DESIGNS[kind];
  if (!rows) throw new Error(`${kind} has no design`);
  return colours.map((name) => {
    if (name === 'Rainbow') return build(rows, 'rainbow');
    if (!CAPS[name]) throw new Error(`${kind}: no cap colours for "${name}"`);
    return build(rows, CAPS[name]);
  });
}
